---
annotations_url: https://www.dropbox.com/s/8j744thrve90kny/imagenet.zip?dl=1
add_all_class_preds: true
priority_transform_modality: image
priority_view_modality: object_id
signal_to_noise_ratio: 0.95
jitter_pool: max
view_pool: max
experiments:
  train_set_full:
    annotations_path: train_set.csv
    num_jitters: 1
    spatial_transform: random
    modalities:
      object_type:
        modality: output
        type: One_vs_Rest
        column_name: object_id
        to_each_view_its_own_label: false
      image:
        modality: input
        type: image_from_filename
        column_name: Filename
        colorspace: Gray
        scale_to: 256
        keep_aspect: true
        width: 224
        height: 224
        model_cfgs:
          model_type: One_to_One
          heads:
          - image
          tails:
          - implicit_image
          neural_net_cfgs:
            neural_net_type: cascade
            block_type: ResNetBasic
            block_output_cs:
            - 64
            - 64
            - 64
            - 64
            block_counts:
            - 1
            - 1
            - 1
            - 1
            kernel_sizes:
            - 3
            - 3
            - 3
            - 3
  val_set:
    annotations_path: val_set.csv
    num_jitters: 1
    spatial_transform: fix
    modalities: same_as_train_set_full
